# Copyright Siemens AG, 2014-2018
# SPDX-License-Identifier:	GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: minimal
dist: trusty

sudo: required

services: docker

env:
  - BASE_IMAGE=debian:jessie
  - BASE_IMAGE=ubuntu:xenial
  - BASE_IMAGE=debian:stretch
  - BASE_IMAGE=ubuntu:bionic
  - BASE_IMAGE=debian:buster

before_script: docker-compose -f src/testing/docker/docker-compose.yml build

script: docker-compose -f src/testing/docker/docker-compose.yml run tests

jobs:
  include:
    - name: Test Official Fossology Docker Image
      env: []
      install: docker-compose build
      script:
        - src/testing/docker/test-cluster.sh
        - src/testing/docker/test-standalone.sh
